### ISSUE TITLE
Filters in query

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/algolia#102]
### Version

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.29`, `@nuxtjs-alt/http@1.4.2`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.2`
- Build Modules:    `-`

### Reproduction Link

I am trying to do a search with filters, but the filters parameter is not getting it for me

`watch(() => input_search.value, () => search({ query: input_search.value, filters: 'domain_list:domain.es'}));`

![image](https://user-images.githubusercontent.com/77386602/198557526-77ffaf86-a96e-4ca3-adbe-8cb9d0ca1f25.png)

![image](https://user-images.githubusercontent.com/77386602/198557782-cea1d959-7825-4960-940c-985581843026.png)

**Comment by Baroshem** [comment]
Hey @agracia-foticos 

To use filters, you should be using `requestOptions` -> https://github.com/nuxt-modules/algolia/blob/03438a1f36d74cbc8d6746d2fdcabffcdc9e3c49/src/runtime/composables/useAlgoliaSearch.ts#L27

So basically, instead of `search({ query: input_search.value, filters: 'domain_list:domain.es'})`

Go with `search({ query: input_search.value, requestOptions: { filters: 'domain_list:domain.es' }})`

Let me know if it works :)

**Comment by agracia-foticos** [comment]
WORKS!!! Thankss!!!!
