### ISSUE TITLE
Monorepo failures due to thrown errors

### ISSUE THREAD

**Issue by genu** [nuxt-modules/algolia#153]
https://github.com/nuxt-modules/algolia/blob/d0af3d9b179d4c3a94d6b5133b8fefab638a5fe6/src/module.ts#L71-L86

I don't think Errors should be thrown here because it will always fail sibling projects. This happens because in a monorepo the nuxt `postinstall` script will always run, which will throw these errors for every project except the nuxt project due to the missing env vars.

Instead of throwing here, warning should be emitted.

**Comment by Baroshem** [comment]
Hey,

Thanks for reporting this.

I intentionally decided to throw errors here because if you run the module without required options (such as apiKey and applicationId) the whole module will not work. Because of that, there is no reason for showing warnings in the console as user may easily miss it and start wondering why the app does not work correctly.

I wouldn't worry about the post-install too much :)
