### ISSUE TITLE
`baseURL` appended twice to the URL when clicking on search result

### ISSUE THREAD

**Issue by Lehoczky** [nuxt-modules/algolia#166]
### Version

"@nuxtjs/algolia": "^1.9.0",
"nuxt": "~3.6.5",

### Reproduction Link

Since DocSearch is only granted for running documentation sites, I'm unfortunately unable to provide a minimal reproduction, but my site is open source. Let me know if you need any help.

Repo: https://github.com/Lehoczky/frontend-tools
Running site: https://lehoczky.github.io/frontend-tools/

### Steps to reproduce

- open the search modal
- search for something, ex: "avoid"
- click on the first result

### What is Expected?

The user is being redirected to https://lehoczky.github.io/frontend-tools/frontend-tools/style-guide/#avoid-mental-mapping which shows the 404 page, because `frontend-tools` is in the URL twice

### What is actually happening?

Navigate to https://lehoczky.github.io/frontend-tools/style-guide/#avoid-mental-mapping instead.

**Comment by Baroshem** [comment]
Hey,

I think that this issue can be caused by the fact that the url property of hit has already the `frontend-tools`.

Because of that the code [here](https://github.com/nuxt-modules/algolia/blob/c4f576266a0d6ae7477228e0ec056d21aac1af32/src/runtime/components/AlgoliaDocSearch.vue#L146C7-L146C7) creates a redirect to the current location with added hit.url that in your case is probably `frontend-tools/something`.

Could you change the url so that it does not include the prefix `frontend-tools`? Then it should be working as expected (for example, nuxt.com uses this Docsearch that way).

**Comment by Lehoczky** [comment]
Hi Jakub,

Isn't the `hit.url` property right here? It is [used as href](https://github.com/nuxt-modules/algolia/blob/c4f576266a0d6ae7477228e0ec056d21aac1af32/src/runtime/components/AlgoliaDocSearch.vue#L136) on the dom and if you click the url in dev tools, it navigates you to the right page:

![image](https://github.com/nuxt-modules/algolia/assets/31937175/f84b1f79-ac37-4e88-8e97-fefdb69074ca)

and it is also equivalent with what [nuxt content](https://content.nuxtjs.org/) generates for that `h3` element:

![image](https://github.com/nuxt-modules/algolia/assets/31937175/924a963a-854c-4412-986e-ff7253716e2c)

`NuxtLink` components also use the base URL:

![image](https://github.com/nuxt-modules/algolia/assets/31937175/9ed1c96a-b45d-4e49-833c-22d9760bcb69)

If I remove the whole base path like this:

```ts
 transformItems(items) {
  return items.map((item) => ({
        ...item,
        url: item.url.replace( 'https://lehoczky.github.io/frontend-tools',  ''),
   }))
},
```

Then clicking on a search result is working, but the `href` is essentially wrong, it should have `frontend-tools` in it. If I click on this link now in the devtools, it goes to the 404 page:

![image](https://github.com/nuxt-modules/algolia/assets/31937175/0b5710e6-3de6-4ed6-89de-afc4a774c6bb)

**Comment by Baroshem** [comment]
Isn't it maybe caused by the `baseUrl` property set in nuxt.config.ts? https://github.com/Lehoczky/frontend-tools/blob/5ca8ec84e2b23e5e004bb2bcc748d630a1b0a57a/nuxt.config.ts#L4

Maybe it is adding this `/frontend-tools` automatically to your url while the link in the DocSearch seems to work correctly.

**Comment by Lehoczky** [comment]
Yes, it's definitely caused by the `baseUrl`, and I think I found the responsible line of code: [nuxt/src/pages/runtime/plugins/router.ts#L53](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/plugins/router.ts#L53)

Because the `useRouter` composable is already using the `baseUrl`, if we `router.push()` anything, like we do [here, in the component](https://github.com/nuxt-modules/algolia/blob/c4f576266a0d6ae7477228e0ec056d21aac1af32/src/runtime/components/AlgoliaDocSearch.vue#L152), that path will get appended to the base url. In my case we push `frontend-tools/anything` while the router is already using `frontend-tools` as a base and that's why we get `frontent-tools/frontend-tools/anything` as a result.
