### ISSUE TITLE
SSR Instantsearch implementation

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-modules/algolia#187]
[Take a look at this](https://github.com/Rigo-m/nuxt-ssr-algolia-example). It's a different (and imho better) way to implement SSR Instantsearch on algolia.
It does not require you to write a carbon copy of the render function of the component, and it's more understandable how it works.

@Baroshem  let me know what you think

**Comment by Baroshem** [comment]
Hey @Rigo-m 

Thanks for this change! I will take a look at it in the upcoming days

**Comment by LoMonacoSalvatore** [comment]
hi @Baroshem! Any news?

**Comment by Baroshem** [comment]
Hey folks,

Sorry for no contact. I have been recently busy with other modules. 

I will set it as a priority to handle this once I will be back from vacation 1st December.

I will review this and possibly merge as it is a good example :)

**Comment by Rigo-m** [comment]
Just a quick follow-up with some ideas:
- We could generalize the ssr plugin and the SSR Provider component so that it can be implemented more easily
- I'm up for an open source instantsearch for vue overhaul. Hit me up on twitter if you want to discuss it, instantsearch implementation in vue/nuxt is not isomorphic, nor performant neither compliant with the vue 3 ecosystem best practices.

**Comment by Baroshem** [comment]
Hey @Rigo-m 

Sorry for long time waiting but I was away for almost two last weeks.

1. This sounds interesting. Do you think this SSR plugin/provider could be a part of the module and be provided in an easy way for the user to use in their Algolia SSR apps with InstantSearch?
2. I am not sure about it. I understant the frustration but this Instantsearch is created by Algolia so I would prefer to keep it in the module if possible because it is official library that majority of users ask for (even if it is not perfect).

I am up for showing your GitHub repo as the example in the documentation if you are ok with that but we can also work on implementing a new version of the module with a feature that could make it simplier for users to work with it :)

**Comment by Rigo-m** [comment]
I think it would be cool to provide it via the module, so that users are encouraged to use the solution and find issues (so that its eventual fix can benefit everyone)

Up to you if you want to provide the components and/or point to this issue in the docs :)
I think the previous solution was bad in many ways that's why i opened this.

As per the point number 2, instantsearch for vue really sucks, if by any means my sorry ass starts to move and I start to do some open source work I really want to rewrite algolia's library for vue from the ground up :D

**Comment by Baroshem** [comment]
So my recommendation will be to add the link right now and if you like and have time, I would really appreciate if you could create a Proof of Concept PR with your solution.

I can add the link to the docs in the upcoming days if you agree :)

Then we could decide how to make it work the best way for the users.

Thanks for all the ideas and dedication for making the module better! 💚

**Comment by Baroshem** [comment]
Added docs mention [here](https://github.com/nuxt-modules/algolia/commit/9460dc14052393669b0a06e0c7f5abc30112fb6c)

**Comment by Rigo-m** [comment]
@Baroshem closing this.
The proposed SSR implementation had many problems that we encountered in real life applications and a bad DX, started working on something better :)

https://github.com/atoms-studio/nuxt-swiftsearch for everyone stumbling across this issue
